# Generated by Django 5.2.4 on 2025-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('tmp', models.FloatField()),
                ('hum', models.FloatField()),
                ('pco', models.FloatField()),
                ('pf', models.FloatField()),
                ('tco', models.FloatField()),
                ('br', models.FloatField()),
                ('pa', models.FloatField()),
                ('vib', models.FloatField()),
                ('dec', models.FloatField()),
                ('eau', models.FloatField()),
            ],
            options={
                'db_table': 'env_data',
                'managed': False,
            },
        ),
    ]
