name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run basic check
        run: echo "✅ Check passed!"
